# -*- coding: utf-8 -*-
"""Semana 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10cG5xRO_TYEsDeQ12CW80SY8cZc191Ey
"""

# Atividade 01 - Escreva um programa que imprima seu nome e sua cidade natal.
print("Alessandro, Rio de Janeiro-RJ")

# Atividade 02 - Crie um programa que pergunte ao usuário seu filme favorito e o ano em que foi lançado, e depois imprima uma mensagem usando essas informações.
filme = input("Qual é seu filme favorito? ")
ano = input("Em que ano ele foi lançado? ")

print("O seu filme favorito " +filme+ ", foi lançado em " +ano+ ".")

# Atividade 03 - Escreva um programa que peça dois números ao usuário e exiba a soma, subtração, multiplicação e divisão deles.

a = int(input("Insira o primeiro número: "))
b = int(input("Insira o segundo número:"))


soma = a + b
sub = a - b
prod = a * b
div = a / b

print("\nSoma:", soma, "\nSubtração:", sub, "\nMultiplicação:", prod, "\nDivisão:", div)

# Atividade 04 - Escreva um programa que peça a temperatura atual e diga se está quente (acima de 30°C), frio (abaixo de 15°C) ou agradável (entre 15°C e 30°C).

t = float(input("Insira a temperatura atual: "))

if t > 30:
    print("Está quente.")

elif t < 15:
    print("Está frio.")

else:
    print("Está agradável.")

# Atividade 05 - Escreva um programa que conte de 1 a 10 e imprima apenas os números pares.

for i in range(1, 11):
    if i % 2 == 0:
     print(i)

# Atividade 06 - Crie um programa que pergunte ao usuário por números até que ele digite zero e então mostre a soma dos números digitados.

soma = 0
n = 1

while n != 0:
    n = float(input("Insira os números para serem somados ou 0 para finalizar: "))
    soma += n

print("A soma dos números digitados é:", soma)

# Atividade 07 - Crie uma lista de compras que permita ao usuário adicionar itens e, em seguida, imprimir a lista completa.

lista = []
item = ""

while item != "fim":
  item = input("Digite o item da lista ou 'fim' para finalizar: ")
  if item != "fim":
    lista.append(item)

for item in lista:
 print("-", item)

# Atividade 08 - Escreva uma função que receba um número e retorne se ele é par ou ímpar.

def par_impar(numero):
    if numero % 2 == 0:
        print(numero, "é Par.")
    else:
        print(numero, "é Ímpar.")

par_impar(50)

# Atividade 09 - Escreva um programa que peça uma frase ao usuário e conte quantas vezes uma letra específica aparece.

texto = input("Insira a frase: ")
l = input("Qual letra? ")
contador = 0

for letra in texto:
  if letra.lower() == l.lower():
    contador += 1

print(f'A letra "{l}" aparece {contador} vez(es) na frase.')

# Atividade 10 - Crie um programa que encontre e imprima todos os números primos em um intervalo definido pelo usuário.

ini = int(input("Insira o primeiro número do intervalo: "))
fim = int(input("Insira o último número do intervalo: "))

def eh_primo(numero):
 if numero <= 1:
  return False
 for i in range(2, int(numero ** 0.5) + 1):
  if numero % i == 0:
    return False
 return True

if ini <= fim:
  print(f"Entre {ini} e {fim}, é(são) primo(s):")
  for numero in range(ini, fim+1):
    if eh_primo(numero):
        print(numero)
else:
  print("Intervalo indevido.")